export default {
  "ur" : [
  { incorrectText: ".", correctText: "۔", completeWord: false },
  { incorrectText: ",", correctText: "،", completeWord: false },
  { incorrectText: " ۔", correctText: "۔", completeWord: false },
  { incorrectText: " - ", correctText: "۔ ", completeWord: false },
  { incorrectText: " ،", correctText: "،", completeWord: false },
  { incorrectText: "?", correctText: "؟", completeWord: false },
  { incorrectText: " ؟", correctText: "؟", completeWord: false },
  { incorrectText: " !", correctText: "!", completeWord: false },
  { incorrectText: "( ", correctText: "(", completeWord: false },
  { incorrectText: " (", correctText: "(", completeWord: false },
  { incorrectText: "ه", correctText: "ہ", completeWord: false },
  { incorrectText: "ک", correctText: "ک", completeWord: false },
  { incorrectText: "ئو", correctText: "ؤ", completeWord: false },
  { incorrectText: "’’", correctText: "”", completeWord: false },
  { incorrectText: "‘‘", correctText: "“", completeWord: false },
  { incorrectText: "…", correctText: "۔۔۔", completeWord: false },
  { incorrectText: "——", correctText: "۔۔۔", completeWord: false },
  { incorrectText: "—", correctText: "۔۔۔", completeWord: false },
  { incorrectText: " ۔۔۔", correctText: "۔۔۔ ", completeWord: false },
  { incorrectText: "،،", correctText: "“", completeWord: false },
  { incorrectText: '۔"', correctText: "۔“", completeWord: false },
  { incorrectText: '، "', correctText: "۔ ”", completeWord: false },
  { incorrectText: '؟"', correctText: "؟“", completeWord: false },
  { incorrectText: '!"', correctText: "!“", completeWord: false },
  { incorrectText: "-", correctText: "۔", completeWord: false },
  { incorrectText: " ، ", correctText: "، ", completeWord: false },
  { incorrectText: " ۔", correctText: "۔ ", completeWord: false },
  { incorrectText: " : ", correctText: ": ", completeWord: false },
  { incorrectText: "آ", correctText: "آ", completeWord: false },
  { incorrectText: "ؤ", correctText: "ؤ", completeWord: false },
  { incorrectText: " ِ", correctText: "ِ", completeWord: false },
  { incorrectText: " ً", correctText: "ً", completeWord: false },
],
"en": [
  { incorrectText: " ۔ ", correctText: "ً۔ ", completeWord: false },
]};
